# Generated by Django 4.2.4 on 2023-09-07 23:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_rename_shippingaddress_shippingaddressmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddressModel',
            new_name='ShippingAddress',
        ),
    ]
