# Generated by Django 4.2.4 on 2023-09-09 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_ordereditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditem',
            old_name='price',
            new_name='unit_price',
        ),
    ]
